# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true

# Mod metadata (shared across all versions)
mod.version=0.2
mod.id=createenergycannons
mod.name=Create Energy Cannons
mod.group=net.arsenalists.createenergycannons
mod.description=This mod adds Energy Cannons to Create using CBC.
mod.authors=HappySG, CeoOfGoogle, Aycer
mod.license=MIT

# Shared dependency versions (same across MC versions)
deps.mixin_extras=0.4.1
